import './globals.scss'
import { Montserrat } from 'next/font/google'
import ContextProvider from './pages/context-provider';

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Chat EF Perfumes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={montserrat.className}>
          <div className="w-full min-h-screen flex items-center justify-center p-8 page">
            <div className='flex items-center justify-center bg-neutral-200 w-full max-h-[90vh] h-[90vh] rounded-md drop-shadow-lg max-w-[2000px] z-10'>
              {children}
            </div>
          </div>
        </body>
      </ContextProvider>
    </html>
  )
}
