import './globals.css'
import { Montserrat } from 'next/font/google'
import UserProvider from './pages/user-context-provider';

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={montserrat.className}>
          {children}
        </body>
      </UserProvider>
    </html>
  )
}
